# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

end
